a=int(input("Enter runs scored by 1st batsman : "))
b=int(input("Enter runs scored by 2nd batsman : "))
c=int(input("Enter runs scored by 3rd batsman : "))
print("Strike rate of 1st batsman : ",+ a/60*100)
print("Strike rate of 2nd batsman : ",+ b/60*100)
print("Strike rate of 3rd batsman : ",+ c/60*100)
print("Runs scored if 1st play 60 balls more : ",+ a*2)
print("Runs scored if 2nd play 60 balls more : ",+ b*2)
print("Runs scored if 3rd play 60 balls more : ",+ c*2)
